from flask import Flask, render_template_string, request
import os
app=Flask(__name__)

PAGE=r'''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cheto Cozy</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f3eee5;color:#40382f;font-family:Arial,sans-serif}.wrap{width:min(760px,92vw);margin:auto;padding:22px 0 110px}.top{position:sticky;top:10px;z-index:9;display:flex;align-items:center;justify-content:space-between;padding:14px 17px;background:#fffaf1e8;border:1px solid #ded3c3;border-radius:22px;backdrop-filter:blur(16px);box-shadow:0 10px 35px #796a5320}.brand{display:flex;align-items:center;gap:12px}.logo{width:44px;height:44px;border-radius:14px;background:#b9855e;color:white;display:grid;place-items:center;font-weight:900;font-size:21px}.brand b{font-size:17px}.brand small{display:block;color:#9b8b7c;margin-top:2px}.lang{border:1px solid #d8cbbb;background:#fffaf3;padding:10px 14px;border-radius:14px;color:#66594d}.hero{padding:60px 4px 30px}.eyebrow{letter-spacing:4px;text-transform:uppercase;color:#a87d5c;font-size:11px;font-weight:bold}.hero h1{font-family:Georgia,serif;font-size:clamp(38px,9vw,68px);line-height:.98;margin:13px 0 17px;font-weight:500}.hero p{color:#7e7064;line-height:1.7;max-width:560px}.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin:18px 0 32px}.stat,.card{background:#fffaf3;border:1px solid #dfd3c3;box-shadow:0 16px 45px #6e5c4414}.stat{border-radius:19px;padding:19px}.stat span{font-size:11px;color:#9a8878;letter-spacing:2px}.stat b{display:block;font-size:20px;margin-top:7px}.title{font-family:Georgia,serif;font-size:28px;margin:35px 0 14px}.card{border-radius:25px;overflow:hidden;margin-bottom:16px;transition:.25s}.card:hover{transform:translateY(-2px)}.visual{height:180px;background:linear-gradient(135deg,#cfa982,#9c7658);position:relative;overflow:hidden}.visual:before,.visual:after{content:"";position:absolute;border-radius:50%;filter:blur(1px)}.visual:before{width:180px;height:180px;background:#f0dbc2aa;right:-35px;top:-65px}.visual:after{width:100px;height:100px;background:#76563c55;left:40px;bottom:-35px}.v2{background:linear-gradient(135deg,#8d9b82,#c4b99e)}.v3{background:linear-gradient(135deg,#a99687,#745f54)}.body{padding:22px}.tag{font-size:10px;letter-spacing:3px;color:#a57958}.body h2{font-family:Georgia,serif;font-weight:500;margin:8px 0;font-size:27px}.body p{color:#817367;line-height:1.55;font-size:13px}.download{display:flex;align-items:center;justify-content:center;gap:9px;width:100%;padding:14px;border:0;border-radius:15px;background:#5e7057;color:#fff;font-weight:bold;font-size:15px;margin-top:17px;box-shadow:0 9px 20px #5e70572c;cursor:pointer}.download:active{transform:scale(.985)}.note{margin-top:38px;padding:22px;border-radius:23px;background:#e8dfd1;color:#756658;text-align:center;line-height:1.6}.float{position:fixed;right:20px;bottom:22px;background:#a87957;color:white;border:0;border-radius:50px;padding:15px 21px;font-weight:bold;box-shadow:0 13px 30px #60452f40}@media(min-width:650px){.stats{grid-template-columns:repeat(4,1fr)}.visual{height:240px}}
</style></head><body><div class="wrap"><header class="top"><div class="brand"><div class="logo">C</div><div><b>CHETO</b><small>Cozy collection</small></div></div><button class="lang">EN⌄</button></header><section class="hero"><div class="eyebrow">Warm · Simple · Calm</div><h1>A softer place<br>for your packs.</h1><p>A clean, cozy download space with warm tones, soft cards and calm motion — inspired by the structure in your video without copying its fire/midnight look.</p></section><div class="stats"><div class="stat"><span>VERSION</span><b>1.0</b></div><div class="stat"><span>BUILD</span><b>64-BIT</b></div><div class="stat"><span>STATUS</span><b>Ready</b></div><div class="stat"><span>REGIONS</span><b>4</b></div></div><h3 class="title">Available packs</h3>
<div class="card"><div class="visual"></div><div class="body"><div class="tag">GLOBAL · 64-BIT</div><h2>Global Pack</h2><p>Prepared for modern devices with a simple, comfortable installation card.</p><button class="download">↓ &nbsp; Download</button></div></div>
<div class="card"><div class="visual v2"></div><div class="body"><div class="tag">KOREA · 64-BIT</div><h2>Korea Pack</h2><p>A dedicated regional package presented in the same warm and minimal style.</p><button class="download">↓ &nbsp; Download</button></div></div>
<div class="card"><div class="visual v3"></div><div class="body"><div class="tag">TAIWAN · 64-BIT</div><h2>Taiwan Pack</h2><p>Everything stays easy to scan, touch-friendly and consistent on mobile.</p><button class="download">↓ &nbsp; Download</button></div></div>
<div class="note">Made for quiet browsing ☕<br><small>No harsh neon, no fire effects — just a warm cozy interface.</small></div></div><button class="float" onclick="scrollTo({top:0,behavior:'smooth'})">↑ Top</button></body></html>'''

@app.route('/')
def home(): return render_template_string(PAGE)

if __name__=='__main__': app.run(host='0.0.0.0',port=int(os.environ.get('PORT',5000)))
